### PR TITLE
Use snake_case for namespace names

### PR DESCRIPTION
**Pull request by Adda0**
This PR refactors namespace names to use snake_case. This allows us to use the following without any name collisions.
```cpp
using namespace mata;
using namespace mata::nfa;
Nfa this_is_nfa_class; // <-- compiler will know that it is a class, not namespace name.
Nfa nfa; // <-- compiler will know it is a variable name, so that
nfa::concatenate(nfa, this_is_nfa_class); // <-- compiler can distinguish between nfa::... and concatenate(nfa, ...).
```

There will be no longer a need to reference `Nfa` class as `Nfa::Nfa`, we can simply use `Nfa`.

I advise the reviewers to review the code commit by commit so that each type of change is easily recognizable. f399c1e07ade20857ebcecefbbdd545716e762d4 only refactors all namespace names to snake_case.

We agreed on these changes, but I ask the assigned reviewers to primarily express in their review whether they agree with the snake_case naming convention for namespace names or not. The review of the changes themselves is optional.

### CODE REVIEW

**Comment by vhavlena** [comment]
I am fine with that. So the current name convention is 

- snake case: namespaces, methods, functions
- camel case: types

?

**Comment by Adda0** [comment]
Basically, yeah. UpperCamelCase (== PascalCase) is what we use for types, type aliases, classes (and structs), enum classes.

**Review by jurajsic — APPROVED** [review]
Looks good, I am ok with these changes

**Comment by Adda0** [comment]
(This force-push only resolves merge conflicts.)

**Review by kilohsakul — APPROVED** [review]

**Review by tfiedor — APPROVED** [review]

**Pull request merged**
