### PR TITLE
Perform a summer cleaning: removing obsolete stuff

### LINKED ISSUE #272: Perform Summer Cleaning
This is related to the discussion about removing useless and outdated stuff: selected examples, cli/misc/unit-test-data directories, and related stuff in e.g. CMakeLists.

### PR DESCRIPTION
**Pull request by tfiedor**
This PR is mostly meant to remove some obsolete parts of libmata and potentially simplify some stuff.

  1. It removes obsolete parts of the mata,
  2. It simplifies (a little) the building of python binding,
  3. It adds GA for building python binding from tarball (this should test installation through pip).

### CODE REVIEW

**Comment by tfiedor** [comment]
I cleaned some stuff that we discussed at last meeting. I included Juraj as well, so you can check or propose, if there is something forgotten, that could be purged from existence.

**Review by Adda0 — APPROVED** [review]
I think you covered everything I know about. This should clean the project nicely.

Could we maybe move the script `merge_static_libraries.sh` into a folder, such as `scripts/`, for example? It pollutes the project root unnecessarily.

**Review by jurajsic — APPROVED** [review]
Great! This was very much needed.

**Comment by Adda0** [comment]
Btw., could you rebase onto the current `devel` to try whether the code coverage GA works as intended? We should now have the `devel` branch coverage as well as the current branch one to see the coverage diff (which should be empty).

**Comment by tfiedor** [comment]
> Btw., could you rebase onto the current `devel` to try whether the code coverage GA works as intended? We should now have the `devel` branch coverage as well as the current branch one to see the coverage diff (which should be empty).

I believe we don't need to rebase, I simply have to fix what I have fucked up right now. The coverage action is already included.

**Comment by Adda0** [comment]
Ah, I see. You are right. No need to rebase, then.

**Comment by Adda0** [comment]
You know what? Maybe we do not need to move the script into a folder after all… :smile:

**Comment by tfiedor** [comment]
> You know what? Maybe we do not need to move the script into a folder after all… 😄

I seriously, do not see what is fucking wrong. Just moving the script should not fuck things up and it works in my local environment, so what the fuck is wrong in the CI.

**Comment by tfiedor** [comment]
(That close was accidental :D)

**Comment by tfiedor** [comment]
I finally fixed the issue @Adda0 . I even rebased to test the Codecov, but it still seems not to work. I hope future PRs will work just fine.

**Comment by tfiedor** [comment]
I rebased old devel, so of course it did not work. Now the coverage fully works. You can merge this @Adda0

**Pull request merged**
