### PR TITLE
fixed a bug in inclusion, added the test case

### PR DESCRIPTION
**Pull request by kilohsakul**
Should not be a big deal ...

### CODE REVIEW

**Comment by martinhruska** [comment]
I've added reviewers. PR is trivial, guys please check it ASAP. I will merge it no later than tommorow.

**Comment by martinhruska** [comment]
@kilohsakul there is a conflict after merge of predicate branch. Could you please solve it? I would do it but I am not sure what is the right version.

**Review by tfiedor — APPROVED** [review]
No comments

**Review by Adda0 — APPROVED** [review]
LGTM. I agree that the change fixes the bug.

**Review by martinhruska — APPROVED** [review]

**Comment by martinhruska** [comment]
@tfiedor could you please fix binding?

**Comment by tfiedor** [comment]
The binding is broken here, because binding is broken on devel ;) so until we fix the broken binding from the previous PR, everything will be broken.

**Pull request merged**
