### PR TITLE
Export headers

### PR DESCRIPTION
**Pull request by martinhruska**
This PR:
- creates `include` folder in `simlib` and `cudd` libraries and changes `#include`s in mata. 
- export the headers files of the mentioned libraries to `/usr/local/include` on `make install`.

### CODE REVIEW

**Review by vhavlena — APPROVED** [review]
It is working in my setting (tried in z3 as well)

**Review by tfiedor — APPROVED** [review]
No comments.

**Review by Adda0 — APPROVED** [review]
LGTM. The Python binding is fixed.

**Comment by martinhruska** [comment]
@jurajsic needs to try `Mintermization`.

**Review by jurajsic — APPROVED** [review]
Mintermization works for me.

**Pull request merged**
