### PR TITLE
Internal algorithms

### PR DESCRIPTION
**Pull request by martinhruska**
This PR:
- creates a new namepace Internal inside Nfa namespace.
- Put functions for complementation, inclusion and universality checking to the new namespace to be accessible to a potential user.
- Creates a new header file for the namespace.

### CODE REVIEW

**Review by Adda0 — APPROVED** [review]
We wanted to call the header file `nfa-algorithms.hh`, but I think that `nfa-internals.hh` might be a better name, as it allows us to potentially use the header file for additional functions which are not strictly “specialized algorithms”.

There was also talk about giving each specialized algorithm a separate source file (one for complement naive, one for complement antichains and so on). With the current state of the algorithms, I do not think it is necessary as of now. However, we have pretty much agreed to make these separate source files for each “specialized algorithm” with a single header file (as it is in this PR) in our last meeting. What do you think? Is it necessary to have separate source files (presumably inside an additional folder `nfa/algorithms/`) `complement_alg1.cc`, `complement_alg2.cc` etc.? I think we can keep the current structure for now. If the files get too cluttered, we can always separate them later.

All in all, I am happy with the PR. The content of the `nfa-internals.hh` will probably grow continuously. This is a good start, I would say.

**Comment by martinhruska** [comment]
I thought about it and imho the current setup is better since it is clearer. Separating every algorithm to its special file would only increase entropy and I don't see any advantages of such set up for now.

**Comment by Adda0** [comment]
I agree. It works for me.

**Comment by tfiedor** [comment]
I will review this later today. I don't like `internals` to be honest, I personally rather prefer `core`, but I think the clearest is Martin's separation: `algorithms`. And then one can have `utils`, or `debug`, or `visualization`, etc. That's clear classification IMO.

**Comment by martinhruska** [comment]
So do you suggest to rename file and namspace to `algorithms`? That makes sense to me.

**Comment by Adda0** [comment]
Theoretically, we can have namespace `internals` with subnamespaces `algorithms`, `utils` etc. That is a bit too much, though, in my opinion.

I am OK with @tfiedor's approach. This depends mainly on how we intend to use these namespaces in the future. For now, we do not have anything to add to the additional namespaces, but we can prepare for when we do. `algorithms`, `utils`, `debug` etc. is definitely more modular and extendable in the future. If we want to have these options for later, I would go with it.

**Comment by tfiedor** [comment]
Sorry, I though Martin named it `algorithms` from start (i'm quite groggy).

I think too much separation is overkill, but too much condensation as well. I think having one file for one class of algorithms is nice. 

As for the `internals` file, if there are only algorithms, I would named it `algorithms`, if there are some other shits, than I would prefer `core` (but `internals` is fine, this is just matter of taste and communities and cliques). Still, If there are some shits I would consider separating algorithms from the shits and call it e.g. `utils` or `helpers`.

**Comment by tfiedor** [comment]
Fair point and reasoning. My minor issue with `internals` is that it sound like something that you should not poke your nose into unless you are the main contributor. Maybe ask Lukas with several options (`core`, `internals`, `global`, `api`, `interface`: just few from top of my head) which sounds to him the most suitable.

**Comment by martinhruska** [comment]
Yes, we should discuss it in the meeting tomorrow with less technical persons :-)

**Comment by martinhruska** [comment]
Ok, does it make sense to rename it to `Algorithms` or should I keep `Internals` since it does not make difference?

**Comment by martinhruska** [comment]
> Ok, does it make sense to rename it to `Algorithms` or should I keep `Internals` since it does not make difference?

??

**Comment by tfiedor** [comment]
> > Ok, does it make sense to rename it to `Algorithms` or should I keep `Internals` since it does not make difference?
> 
> ??

I though we said we should rename it to Algorithms?

**Comment by martinhruska** [comment]
Yes, we agreed on that. My question was whether it makes sense. Is it really better name? If it is, I'm gonna rename it.

**Comment by tfiedor** [comment]
Since, now, after review, I saw there are only algorithms, I think it makes sense.

**Comment by martinhruska** [comment]
Renaming done.

**Review by Adda0 — APPROVED** [review]
LGTM.

**Pull request merged**
