### PR TITLE
Readme Update

### PR DESCRIPTION
**Pull request by vhavlena**
Fixing `README.md` to be more up-to-date.

### CODE REVIEW

**Review by Adda0 — COMMENTED** [review]
LGTM. Do you plan to resolve the remaining tasks in #319 in this PR?

**Review by jurajsic — APPROVED** [review]
Looks fine.

**Comment by vhavlena** [comment]
> LGTM. Do you plan to resolve the remaining tasks in #319 in this PR?

I was not aware of this Issue. Maybe I include something that makes sense to me.

**Comment by Adda0** [comment]
Sounds good to me. Let me know when you have finished working on this PR, and the PR is ready for final review.

**Comment by vhavlena** [comment]
Ok, it is ready now. Please look at it.

**Review by Adda0 — APPROVED** [review]
LGTM. Thanks for the additions. Do you want to request anybody to (re)review the changes before merging?

**Comment by vhavlena** [comment]
I think we can merge it.

**Pull request merged**
