### PR TITLE
Move building CUDD from Autoconf to CMake

### PR DESCRIPTION
**Pull request by jurajsic**

### CODE REVIEW

**Comment by martinhruska** [comment]
PR does what it promises. It breaks my heart that we are gonna lose those beatifull autconf tools.

**Review by martinhruska — APPROVED** [review]
No issues, I am happy that we get rid of that `build-aux` mess.

**Review by Adda0 — APPROVED** [review]
Looks good to me. CUDD is easier to with and to include now. I see this as a success.

**Review by tfiedor — APPROVED** [review]
Seems fine

**Pull request merged**
