### PR TITLE
Jupyter notebook for visualization

### PR DESCRIPTION
**Pull request by vhavlena**
Notebook showing possibilities of automata visualisation in mata.

### CODE REVIEW

**Comment by Adda0** [comment]
This was badly needed. I will review the PR later today as soon as I can. From the quick glance, the PR seems nice.

**Comment by vhavlena** [comment]
@kilohsakul maybe wanted to include such a notebook to the paper. Lukas, please look at it.

**Review by Adda0 — APPROVED** [review]
LGTM. I think we should add one of the examples to the paper.

**Comment by kilohsakul** [comment]
Krasne! Jeste by to fakt mohlo kreslit horizontalne.

**Comment by vhavlena** [comment]
I think it is ready for merge.

**Review by tfiedor — APPROVED** [review]
I think it is fine, probably remove those commented lines though, if they are not used anywhere.

**Comment by Adda0** [comment]
Let me know if you want to remove the commented out lines or merge the PR right away.

**Pull request merged**
