### PR TITLE
Improve the project environment

### PR DESCRIPTION
**Pull request by tfiedor**
This pull request improves the current environment of the project, in particular:

1.  It adds basic readme for the project, with all of the necessary information,
2. Add documentation with target to HTML/PDF/etc.,
3. Add automatization of deployment of documentation to gh-pages,
4. Add automatical tag of new version,
5. Polishes some minor things.

### CODE REVIEW

**Comment by tfiedor** [comment]
The results can be demonstrated (for now) at my fork: https://github.com/tfiedor/mata

**Comment by martinhruska** [comment]
Looks fine to me. The only thing I am not sure about is removing the old complex examples in `vtf` format. It looks like a huge amount of work which can be eventually useful. Maybe we should rather consider to convert it to the actual format and library API.

**Review by martinhruska — APPROVED** [review]

**Comment by tfiedor** [comment]
Yes, that can be done. We shall discuss it during the meeting.

**Comment by tfiedor** [comment]
@martinhruska I have restored the old example, made them compilable, however, not necessarily correct. The format needs to be changed in the added .mf files and the functionality has to be verified, preferably by someone who knows what it should do. If the checks pass and you don't want to wait for ondra, then merge it.

**Comment by martinhruska** [comment]
I am fine with PR now. Going to merge it.

**Pull request merged**
