### PR TITLE
Get git hash

### LINKED ISSUE #243: Get Mata version at runtime
When running experiments on benchmarks, it is useful to know which Mata version was used. This is especially needed for testing Noodler.

We need to implement function `Mata::get_version()` for getting the Mata version of the currently compiled binary. The version is detected and stored during compilation using CMake (probably), presumably stored as a text file, or in a CMake generated source file `.cc` compiled together with Mata (might be a better approach considering you do not have to handle where and how to store the text file). The requested function then reads the file and returns the current Mata version.

### PR DESCRIPTION
**Pull request by jurajsic**
This PR creates a variable `g_GIT_SHA1` in which we keep the current git hashcode.

### CODE REVIEW

**Review by tfiedor — APPROVED** [review]
Seems fine, but can you elaborate the usage? Why is it necessary?

**Comment by Adda0** [comment]
@tfiedor Look at the linked issue. That should explain the reason for this PR.

**Review by Adda0 — APPROVED** [review]
Looks good to me. Mata still fails to build on my system without modifications to CMakeLists.txt, but as it appears, it is OK elsewhere. And I can manage.

**Comment by Adda0** [comment]
@tfiedor Unless you are unsatisfied with the example use cases given in the linked issue, the PR is ready to be merged. Can we proceed?

**Comment by tfiedor** [comment]
No, I have no issue with that, since I approved :) you can merge, I was just wondering why since it is quite unusual change.

**Pull request merged**
