### PR TITLE
In-place Union

### PR DESCRIPTION
**Pull request by vhavlena**
In-place union in the concat style

### CODE REVIEW

**Review by tfiedor — APPROVED** [review]

**Review by kilohsakul — APPROVED** [review]

**Review by kilohsakul — COMMENTED** [review]
supr

**Comment by kilohsakul** [comment]
Let's merge it, no? This one does not need discussion.

**Comment by tfiedor** [comment]
I will merge it later. I am going to my home planet now.

**Comment by kilohsakul** [comment]
Actually, can you add some short comment on what it does and how,
and patch around the case when one is uniting with himself?
You could also patch this around in concatenation.
I guess just test that the referenes are the same or something and if yes then make a coppy first?

**Comment by kilohsakul** [comment]
Actually, one more thing :). Sorry for being pain.
The out of place union should call the inplace union on a coppy of the automaton.

I hope we do the coppy somehow intelligently, not transition by transition, is that right?

**Comment by vhavlena** [comment]
> Actually, can you add some short comment on what it does and how,
> and patch around the case when one is uniting with himself?
> You could also patch this around in concatenation.
> I guess just test that the referenes are the same or something and if yes then make a coppy first?

Not pretty sure how to do it efficiently. The comparison `==` actually compares structures and not that they reference the same thing in memory. Moreover, the comparison call might be expensive.

**Comment by vhavlena** [comment]
> Actually, one more thing :). Sorry for being pain. The out of place union should call the inplace union on a coppy of the automaton.
> 
> I hope we do the coppy somehow intelligently, not transition by transition, is that right?

But in that case we need to remove the `const` qualifier from first parameter in the `uni` function. The second thing is that it is not quite intuitive to use function that returns a result and in fact modifies one of the parameters.

**Comment by vhavlena** [comment]
I tried to resolve Lukas's comments.

**Comment by kilohsakul** [comment]
thanks.
Not sure whether this is relevant any more, but to figure out that we have the same object, can't we do just something like this?
return &a == &b or 
#include <memory> //std::addressof
bool AreEqual(const Class& a, const Class& b)
{
  return std::addressof(a) == std::addressof(b);
}
https://stackoverflow.com/questions/12403659/can-you-compare-objects-by-address-for-equality

**Comment by vhavlena** [comment]
> thanks.
> Not sure whether this is relevant any more, but to figure out that we have the same object, can't we do just something like this?
> return &a == &b or
> #include //std::addressof
> bool AreEqual(const Class& a, const Class& b)
> {
> return std::addressof(a) == std::addressof(b);
> }
> https://stackoverflow.com/questions/12403659/can-you-compare-objects-by-address-for-equality

Yeah, sure, easy :) It is not relevant now. I used copy of spare sets instead of the whole automaton. Should be hopefully ok now (even for the concatenation)

**Comment by tfiedor** [comment]
The rest of the reviewers can check this out later. The checks are OK, I'm merging the fuck out of this bitch.

**Review by Adda0 — COMMENTED** [review]
Looks good to me. I have nothing to discuss.

**Pull request merged**
