### PR TITLE
renamed files with _ to -

### PR DESCRIPTION
**Pull request by martinhruska**
This PR just renames file containing `_` in their names to `-`. Please check I didn't break anything unintentionally.

### CODE REVIEW

**Review by tfiedor — APPROVED** [review]
Well, I have no issues with this PR. But why? Why do we want to change `_` to `-`, since `_` is C++ style O.o. Maybe we talked about it somewhere, but I don't recall discussing this.

**Comment by martinhruska** [comment]
It's mentioned in #78. And I chose `-` because it was originally used in MATA. `_` is import from the old VATA.

**Comment by tfiedor** [comment]
I see, sorry, I omited the original thread for some reason. I would prefer `_` since, Python doesn't support `-` in names. And this way it will be uniform with binding. But I will not champion this in any way.

**Comment by martinhruska** [comment]
Yes, but renaming everything to `_` would be a lot of work and it would conflict with other branches. I am not sure if we want to make this investment now.

**Review by Adda0 — APPROVED** [review]
I am fine with the PR, even though I myself would prefer `_` in the file names as well. As of now, this simple change unifies file names in the whole library (except the Python binding, of course), which I consider a good thing. Let us therefore use the names with `-` from now on. We can switch to `_` later, if we so desire.

**Pull request merged**
