### PR TITLE
Proper handling of constants (true/false)

### LINKED ISSUE #174: Constants (true/false) in FormulaNode
Currently the constants true/false are not represented in FormulaNode in any way and to check if it is there, we need to check for the name of the node. In #169 I added function is_constant(), is_true() and is_false(), but they also only check for the name of the node. Maybe we should add an option to enum of the node representing a constant operand true/false.

### PR DESCRIPTION
**Pull request by jurajsic**
This PR solves #174, i.e. it adds true/false as its own operator type in intermediate automaton and also changes the parser so that constants are given as `\true`/`\false` as we agreed in #168

### CODE REVIEW

**Review by Adda0 — APPROVED** [review]
The changes look good to me.

**Comment by Adda0** [comment]
@martinhruska If you do not want or do not have the time, you do not have to review the code. But it might be beneficial to know about the change for when you work on further parser changes.

**Review by tfiedor — APPROVED** [review]
OK. Did you try running this on the changes from the nfa-bench repo to verify it works OK?

**Comment by jurajsic** [comment]
> OK. Did you try running this on the changes from the nfa-bench repo to verify it works OK?

It looks like it works for few I tried.

**Pull request merged**
