### PR TITLE
adding domain_size to NumberPredicate

### PR DESCRIPTION
**Pull request by kilohsakul**
just the domain_size for NumberPredicate

### CODE REVIEW

**Review by martinhruska — APPROVED** [review]
The function makes sense. I like the name of function. On the other hand, I would consider naming these kind of function just `size()` to be compatible with STL.

**Comment by martinhruska** [comment]
I will wait with merging this PR for the fix of Python binding. I suggest to wait until tommorow afternoon and start merging pending PRs regardless of the state of binding.

**Comment by tfiedor** [comment]
I won't be fixing binding in this PR, as the changes could not have broken anything. (As I said,) the binding is inherently broken from the devel, hence any PR is transitively broken.

**Comment by martinhruska** [comment]
I understand the problem and I expect that they will be also transitively fixed :-)

**Comment by kilohsakul** [comment]
> 

size() is already there, it is something else - the size of the reprented set.

**Comment by kilohsakul** [comment]
added also truncate_domain

**Comment by kilohsakul** [comment]
dosahl jsem dokonaly pocet pridanych radku, nebudu uz nic menit

**Review by martinhruska — APPROVED** [review]

**Pull request merged**
